services:
    mukadi_chart_js.builder:
        class: Mukadi\ChartJSBundle\Model\SimpleChartBuilder
        arguments: ["@doctrine.orm.entity_manager"]
    mukadi_chart_Js.twig_extension:
        class: Mukadi\ChartJSBundle\Twig\ChartJSExtension
        arguments: [@twig]
        tags:
            - { name : twig.extension }